
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - calculator_api
      - calculation_history_api
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"    # AMQP (App connection)
      - "15672:15672"  # Admin/Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  calculator_api:
    build:
      context: .
      dockerfile: calculator_api/Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_QUEUE=calculations
      - PORT=8080
    depends_on:
      rabbitmq:
        condition: service_healthy

  calculation_history_api:
    build:
      context: .
      dockerfile: calculation_history_api/Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_QUEUE=calculations
      - PORT=8081
      - RABBITMQ_QUEUE_SIZE=5
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
