events {}

http {
    server {
        listen 80;

        location /api/calculations {
            proxy_pass http://calculator_api:8080;
        }

        location /api/history {
            proxy_pass http://calculation_history_api:8081;
        }

        location /api/register {
            proxy_pass http://authentication_api:8082;
        }

        location /api/login {
            proxy_pass http://authentication_api:8082;
        }
    }
}
