### POST request to calculate basic expression
POST {{calculator_url}}/api/calculations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "expression": "23*34-45/3+15"
}

### POST request to calculate advanced expression
POST {{calculator_url}}/api/calculations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "expression": "3^2*PI*SIN(35)+SQRT(65)"
}
